version: 2
updates:
  # Python deps from requirements*.txt / pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Group all Python bumps into a single PR (we can tweak later if too big)
    groups:
      python-deps:
        patterns:
          - "*"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"

  # Bump base images & FROM tags in your Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"
