apiVersion: v2
name: rickmorty
description: Rick & Morty API glue service (FastAPI) with HPA, Ingress, and log sidecar
type: application
version: 0.1.0
appVersion: "0.6.0"
dependencies:
  - name: postgresql
    version: 15.5.11
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled