name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # Make handles venv creation + installs (no activation needed)
      - name: Install deps (runtime + dev)
        run: make dev

      - name: Lint
        run: make lint

      - name: Test (coverage >= 80%)
        run: make test

      - name: Generate HTML coverage (only on 3.12)
        if: matrix.python-version == '3.12'
        run: make coverage

      - name: Upload coverage HTML artifact
        if: matrix.python-version == '3.12'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ github.run_id }}
          path: htmlcov/
          if-no-files-found: warn

  e2e-test:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install deps (runtime + e2e)
        run: |
          make install
          pip install -r requirements-e2e.txt

      - name: Setup Kind cluster and run e2e tests
        run: |
          make kind-up
          make test-e2e

      - name: Cleanup Kind cluster
        if: always()
        run: make kind-down
